## Data Cleaning Notebook

1. Cleaning the raw extracted data from airbnb stored at `"../Data/raw/Airbnbdata` to a clean csv ready for analysis and model training
2. Further cleaning after scrabbing extra columns data

In [6]:
import pandas as pd
import json

with open(r"../Data/raw/Airbnbdata.json", encoding="utf-8") as f:
    data = json.load(f)

if isinstance(data, dict):
    data = [data]

df = pd.json_normalize(data)

df.columns = (
    df.columns
    .str.replace('.', '_')  
    .str.lower()             
)

if 'price_price' in df.columns:
    df['price_price'] = (
        df['price_price']
        .astype(str)
        .str.replace('$', '', regex=False)
        
    )

print("Shape:", df.shape)

Shape: (833, 36)

In [7]:
df.head()

,thumbnail,id,title,description,url,rating_accuracy,rating_checking,rating_cleanliness,rating_communication,rating_location,...,price_breakdown_cleaningfee,price_breakdown_specialoffer,price_breakdown_earlybirddiscount,coordinates_latitude,coordinates_longitude,price_breakdown_specialoffer_price,price_breakdown_specialoffer_description,rating,price_breakdown_taxes_price,price_breakdown_taxes_description
0,https://a0.muscache.com/im/pictures/hosting/Ho...,1292713234154945394,"ETERNA.Suite W Jaccuzi, Pyramids View & Balcony",Enjoy your stay with Panoramic View of the Giz...,https://www.airbnb.com/rooms/12927132341549453...,4.96,4.94,4.92,4.97,4.79,...,None,NaN,None,29.973873,31.146603,NaN,NaN,NaN,NaN,NaN
1,https://a0.muscache.com/im/pictures/hosting/Ho...,1508718511630646313,king khufu suite,Welcome To Marhaba Pyramids View Hotel✨Wake up...,https://www.airbnb.com/rooms/15087185116306463...,5.00,4.95,5.00,5.00,4.85,...,None,NaN,None,29.986300,31.143100,NaN,NaN,NaN,NaN,NaN
2,https://a0.muscache.com/im/pictures/hosting/Ho...,1297327219631789358,Akasia Pyramids View,The place is spacious and can accommodate more...,https://www.airbnb.com/rooms/12973272196317893...,4.91,4.85,4.91,4.97,4.78,...,None,NaN,None,29.978100,31.145400,NaN,NaN,NaN,NaN,NaN
3,https://a0.muscache.com/im/pictures/hosting/Ho...,1606001853199411128,Mountain Cave | Pyramids View & Jacuzzi,A designer retreat where ancient soul meets mo...,https://www.airbnb.com/rooms/16060018531994111...,5.00,4.83,4.75,4.92,4.75,...,None,NaN,None,29.979090,31.146920,NaN,NaN,NaN,NaN,NaN
4,https://a0.muscache.com/im/pictures/miso/Hosti...,1314833467096489875,Heaven of Pyramids,Enjoy stay in Single RoomTHE ROOM FEATURES1 Qu...,https://www.airbnb.com/rooms/13148334670964898...,4.74,4.84,4.61,4.80,4.66,...,None,NaN,None,29.978787,31.144191,NaN,NaN,NaN,NaN,NaN

#### Select the relevant columns for analysis

In [8]:

cols_to_keep = [
    "id", "title", "url", "thumbnail",
    "coordinates_latitude", "coordinates_longitude",
    "rating_guestsatisfaction", "rating_reviewscount",
    "rating_accuracy", "rating_cleanliness",
    "rating_value", "rating_location",
    "price_price", "price_originalprice",
    "price_breakdown_specialoffer_price",
    "description"
]

cols_to_keep = [c for c in cols_to_keep if c in df.columns]
df = df[cols_to_keep].copy()

df.head()

,id,title,url,thumbnail,coordinates_latitude,coordinates_longitude,rating_guestsatisfaction,rating_reviewscount,rating_accuracy,rating_cleanliness,rating_value,rating_location,price_price,price_originalprice,price_breakdown_specialoffer_price,description
0,1292713234154945394,"ETERNA.Suite W Jaccuzi, Pyramids View & Balcony",https://www.airbnb.com/rooms/12927132341549453...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.973873,31.146603,4.95,133.0,4.96,4.92,4.92,4.79,675,$750,NaN,Enjoy your stay with Panoramic View of the Giz...
1,1508718511630646313,king khufu suite,https://www.airbnb.com/rooms/15087185116306463...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.986300,31.143100,5.00,62.0,5.00,5.00,4.97,4.85,527,None,NaN,Welcome To Marhaba Pyramids View Hotel✨Wake up...
2,1297327219631789358,Akasia Pyramids View,https://www.airbnb.com/rooms/12973272196317893...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.978100,31.145400,4.91,176.0,4.91,4.91,4.95,4.78,194,None,NaN,The place is spacious and can accommodate more...
3,1606001853199411128,Mountain Cave | Pyramids View & Jacuzzi,https://www.airbnb.com/rooms/16060018531994111...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.979090,31.146920,4.92,12.0,5.00,4.75,4.58,4.75,593,None,NaN,A designer retreat where ancient soul meets mo...
4,1314833467096489875,Heaven of Pyramids,https://www.airbnb.com/rooms/13148334670964898...,https://a0.muscache.com/im/pictures/miso/Hosti...,29.978787,31.144191,4.71,125.0,4.74,4.61,4.80,4.66,117,None,NaN,Enjoy stay in Single RoomTHE ROOM FEATURES1 Qu...

#### Rename the columns for clarity

In [9]:
# to rename the columns names
df.rename(columns={
    "coordinates_latitude":               "lat",
    "coordinates_longitude":              "lng",
    "rating_guestsatisfaction":           "rating_overall",
    "rating_reviewscount":                "reviews_count",
    "price_price":                        "price_total",
    "price_originalprice":                "price_original",
    "price_breakdown_specialoffer_price": "discount_amount",
    
}, inplace=True)
df.head()

,id,title,url,thumbnail,lat,lng,rating_overall,reviews_count,rating_accuracy,rating_cleanliness,rating_value,rating_location,price_total,price_original,discount_amount,description
0,1292713234154945394,"ETERNA.Suite W Jaccuzi, Pyramids View & Balcony",https://www.airbnb.com/rooms/12927132341549453...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.973873,31.146603,4.95,133.0,4.96,4.92,4.92,4.79,675,$750,NaN,Enjoy your stay with Panoramic View of the Giz...
1,1508718511630646313,king khufu suite,https://www.airbnb.com/rooms/15087185116306463...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.986300,31.143100,5.00,62.0,5.00,5.00,4.97,4.85,527,None,NaN,Welcome To Marhaba Pyramids View Hotel✨Wake up...
2,1297327219631789358,Akasia Pyramids View,https://www.airbnb.com/rooms/12973272196317893...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.978100,31.145400,4.91,176.0,4.91,4.91,4.95,4.78,194,None,NaN,The place is spacious and can accommodate more...
3,1606001853199411128,Mountain Cave | Pyramids View & Jacuzzi,https://www.airbnb.com/rooms/16060018531994111...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.979090,31.146920,4.92,12.0,5.00,4.75,4.58,4.75,593,None,NaN,A designer retreat where ancient soul meets mo...
4,1314833467096489875,Heaven of Pyramids,https://www.airbnb.com/rooms/13148334670964898...,https://a0.muscache.com/im/pictures/miso/Hosti...,29.978787,31.144191,4.71,125.0,4.74,4.61,4.80,4.66,117,None,NaN,Enjoy stay in Single RoomTHE ROOM FEATURES1 Qu...

#### Checking for nulls

In [10]:
print(df.isnull().sum())
print("\n")

id                      0
title                  50
url                     0
thumbnail               0
lat                     2
lng                     2
rating_overall        366
reviews_count         366
rating_accuracy       366
rating_cleanliness    366
rating_value          366
rating_location       366
price_total             0
price_original        530
discount_amount       606
description             0
dtype: int64

In [11]:
df.columns

Index(['id', 'title', 'url', 'thumbnail', 'lat', 'lng', 'rating_overall',
       'reviews_count', 'rating_accuracy', 'rating_cleanliness',
       'rating_value', 'rating_location', 'price_total', 'price_original',
       'discount_amount', 'description'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 833 entries, 0 to 832
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  833 non-null    object
 1   title               783 non-null    object
 2   url                 833 non-null    object
 3   thumbnail           833 non-null    object
 4   lat                 831 non-null    float64
 5   lng                 831 non-null    float64
 6   rating_overall      467 non-null    float64
 7   reviews_count       467 non-null    float64
 8   rating_accuracy     467 non-null    float64
 9   rating_cleanliness  467 non-null    float64
 10  rating_value        467 non-null    float64
 11  rating_location     467 non-null    float64
 12  price_total         833 non-null    object
 13  price_original      303 non-null    object
 14  discount_amount     227 non-null    object
 15  description         833 non-null    object
dtypes: float64(8), object(8)
memory usage: 104.3+ KB

### Checking duplicates

In [13]:
df.duplicated().sum()

np.int64(0)

### Checking Nulls count

In [14]:
df.isna().sum()

id                      0
title                  50
url                     0
thumbnail               0
lat                     2
lng                     2
rating_overall        366
reviews_count         366
rating_accuracy       366
rating_cleanliness    366
rating_value          366
rating_location       366
price_total             0
price_original        530
discount_amount       606
description             0
dtype: int64

### Add `has_rating` flag according to rating
Keep track of the replaced nulls

In [15]:
df['has_rating'] = df['rating_overall'].notna()

### Price data cleaning
- remove non-numeric values
- Convert to float

In [16]:
df['price_total'] = df['price_total'].replace('[^0-9.]', '', regex=True)
df['price_original'] = df['price_original'].replace('[^0-9.]', '', regex=True)
df['discount_amount'] = df['discount_amount'].replace('[^0-9.]', '', regex=True)

In [17]:
df['price_total'] = pd.to_numeric(df['price_total'], errors='coerce')
df['price_original'] = pd.to_numeric(df['price_original'], errors='coerce')
df['discount_amount'] = pd.to_numeric(df['discount_amount'], errors='coerce')

### Nulls Handling

In [18]:
# title
df['title'] = df['title'].fillna('Unknown')

# prices
df['price_original'] = df['price_original'].fillna(df['price_total'])

# discount
df['discount_amount'] = df['discount_amount'].fillna(
    df['price_original'] - df['price_total']
).clip(lower=0)

# reviews
df['reviews_count'] = df['reviews_count'].fillna(0)

# drop rows without location
df = df.dropna(subset=['lat', 'lng']).copy()

# ratings
rating_cols = [
    'rating_overall',
    'rating_accuracy',
    'rating_cleanliness',
    'rating_value',
    'rating_location'
]

for col in rating_cols:
    df[col] = df[col].fillna(df[col].mean())

# check
print(df[rating_cols].isna().sum())

rating_overall        0
rating_accuracy       0
rating_cleanliness    0
rating_value          0
rating_location       0
dtype: int64

In [19]:
print(df.isna().sum())
df.head()

id                    0
title                 0
url                   0
thumbnail             0
lat                   0
lng                   0
rating_overall        0
reviews_count         0
rating_accuracy       0
rating_cleanliness    0
rating_value          0
rating_location       0
price_total           0
price_original        0
discount_amount       0
description           0
has_rating            0
dtype: int64

,id,title,url,thumbnail,lat,lng,rating_overall,reviews_count,rating_accuracy,rating_cleanliness,rating_value,rating_location,price_total,price_original,discount_amount,description,has_rating
0,1292713234154945394,"ETERNA.Suite W Jaccuzi, Pyramids View & Balcony",https://www.airbnb.com/rooms/12927132341549453...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.973873,31.146603,4.95,133.0,4.96,4.92,4.92,4.79,675,750.0,75.0,Enjoy your stay with Panoramic View of the Giz...,True
1,1508718511630646313,king khufu suite,https://www.airbnb.com/rooms/15087185116306463...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.986300,31.143100,5.00,62.0,5.00,5.00,4.97,4.85,527,527.0,0.0,Welcome To Marhaba Pyramids View Hotel✨Wake up...,True
2,1297327219631789358,Akasia Pyramids View,https://www.airbnb.com/rooms/12973272196317893...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.978100,31.145400,4.91,176.0,4.91,4.91,4.95,4.78,194,194.0,0.0,The place is spacious and can accommodate more...,True
3,1606001853199411128,Mountain Cave | Pyramids View & Jacuzzi,https://www.airbnb.com/rooms/16060018531994111...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.979090,31.146920,4.92,12.0,5.00,4.75,4.58,4.75,593,593.0,0.0,A designer retreat where ancient soul meets mo...,True
4,1314833467096489875,Heaven of Pyramids,https://www.airbnb.com/rooms/13148334670964898...,https://a0.muscache.com/im/pictures/miso/Hosti...,29.978787,31.144191,4.71,125.0,4.74,4.61,4.80,4.66,117,117.0,0.0,Enjoy stay in Single RoomTHE ROOM FEATURES1 Qu...,True

#### convert the strings to float

In [20]:
cols = [
    'rating_overall',
    'reviews_count',
    'rating_accuracy',
    'rating_cleanliness',
    'rating_value',
    'rating_location',
    'price_total',
    'price_original',
    'discount_amount'
]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

#### Save the cleaning data in csv file

In [34]:
df.to_csv("../Data/clean/airbnb_cleaneddataV1.csv", index=False, encoding="utf-8-sig")

## Further Cleaning 
(After scrabbing bedrooms and bathrooms data and saving to `airbnb_cleaneddataV1.csv`)

In [41]:
df2 = pd.read_csv('../Data/clean/airbnb_cleaneddataV1.csv')
df2.head()

,id,title,url,thumbnail,lat,lng,rating_overall,reviews_count,rating_accuracy,rating_cleanliness,rating_value,rating_location,price_total,price_original,discount_amount,description,has_rating,bedrooms,bathrooms
0,1292713234154945394,"ETERNA.Suite W Jaccuzi, Pyramids View & Balcony",https://www.airbnb.com/rooms/12927132341549453...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.973873,31.146603,4.95,133.0,4.96,4.92,4.92,4.79,675,750.0,75.0,Enjoy your stay with Panoramic View of the Giz...,True,1,1.0
1,1508718511630646313,king khufu suite,https://www.airbnb.com/rooms/15087185116306463...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.986300,31.143100,5.00,62.0,5.00,5.00,4.97,4.85,527,527.0,0.0,Welcome To Marhaba Pyramids View Hotel✨Wake up...,True,1,NaN
2,1297327219631789358,Akasia Pyramids View,https://www.airbnb.com/rooms/12973272196317893...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.978100,31.145400,4.91,176.0,4.91,4.91,4.95,4.78,194,194.0,0.0,The place is spacious and can accommodate more...,True,1,1.0
3,1606001853199411128,Mountain Cave | Pyramids View & Jacuzzi,https://www.airbnb.com/rooms/16060018531994111...,https://a0.muscache.com/im/pictures/hosting/Ho...,29.979090,31.146920,4.92,12.0,5.00,4.75,4.58,4.75,593,593.0,0.0,A designer retreat where ancient soul meets mo...,True,1,1.0
4,1314833467096489875,Heaven of Pyramids,https://www.airbnb.com/rooms/13148334670964898...,https://a0.muscache.com/im/pictures/miso/Hosti...,29.978787,31.144191,4.71,125.0,4.74,4.61,4.80,4.66,117,117.0,0.0,Enjoy stay in Single RoomTHE ROOM FEATURES1 Qu...,True,1,NaN

In [42]:
df2.isnull().sum()

id                      0
title                   0
url                     0
thumbnail               0
lat                     0
lng                     0
rating_overall          0
reviews_count           0
rating_accuracy         0
rating_cleanliness      0
rating_value            0
rating_location         0
price_total             0
price_original          0
discount_amount         0
description            53
has_rating              0
bedrooms               45
bathrooms             108
dtype: int64

In [43]:
df2['bathrooms'] = df2['bathrooms'].fillna(df2['bathrooms'].mode()[0])
df2['bedrooms'] = df2['bedrooms'].fillna(df2['bedrooms'].mode()[0])
df2.isnull().sum()

id                     0
title                  0
url                    0
thumbnail              0
lat                    0
lng                    0
rating_overall         0
reviews_count          0
rating_accuracy        0
rating_cleanliness     0
rating_value           0
rating_location        0
price_total            0
price_original         0
discount_amount        0
description           53
has_rating             0
bedrooms               0
bathrooms              0
dtype: int64

In [44]:
df2['bedrooms'] = df2['bedrooms'].replace('0 (studio)', 0)
df2['bedrooms'] = pd.to_numeric(df2['bedrooms'], errors='coerce')

In [45]:
df2.to_csv('../Data/clean/airbnb_cleaned.csv',index=False, encoding="utf-8-sig")